<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Plotty</title>
<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet'
	type='text/css' />
<script src="https://use.fontawesome.com/efdfda4849.js"></script>
<link href="/css/default.css" rel="stylesheet" media="screen"
	type="text/css" />
</head>
<body>
	<div class="topbar">
		<div class="top-title">
			<a href="/"><i class="fa fa-share-alt" aria-hidden="true"></i> Plotty</a>
		</div>
		<div class="top-subtitle">a wormhole probing tool for EVE-Online
			players</div>
	</div>
        <?php if (isset($name)) : ?>
            
        <?php else: ?>
        
        <?php endif; ?>
</body>
</html>
